In [3]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\katla\Documents\ml-technical-assessment\us-counties.csv")
df.head()

,date,geoid,county,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,USA-53061,Snohomish,Washington,1,0.14,0.02,0,0.0,0.0
1,2020-01-22,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
2,2020-01-23,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
3,2020-01-24,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
4,2020-01-24,USA-17031,Cook,Illinois,1,0.14,0.00,0,0.0,0.0

In [9]:
df['date']=pd.to_datetime(df['date'])
df=df.sort_values(by='date').reset_index(drop=True)

In [10]:
print(df.isnull().sum())

date                       0
geoid                      0
county                     0
state                      0
cases                      0
cases_avg                  0
cases_avg_per_100k     20770
deaths                     0
deaths_avg                 0
deaths_avg_per_100k    20770
dtype: int64

In [11]:
df.tail()

,date,geoid,county,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
1774199,2021-09-29,USA-30009,Carbon,Montana,6,3.86,35.96,0,0.00,0.00
1774200,2021-09-29,USA-01035,Conecuh,Alabama,1,4.43,36.70,0,0.14,1.18
1774201,2021-09-29,USA-01037,Coosa,Alabama,6,8.57,80.38,0,0.43,4.02
1774202,2021-09-29,USA-01009,Blount,Alabama,23,34.57,59.79,0,1.14,1.98
1774203,2021-09-29,USA-78010,St. Croix,Virgin Islands,35,17.57,34.73,0,0.14,0.28

In [12]:
df.describe()

,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
count,1774204,1.774204e+06,1.774204e+06,1.753434e+06,1.774204e+06,1.774204e+06,1.753434e+06
mean,2020-12-30 07:34:32.525594880,2.444017e+01,2.523847e+01,2.484046e+01,3.909049e-01,3.999916e-01,4.298328e-01
min,2020-01-21 00:00:00,-1.239550e+05,0.000000e+00,0.000000e+00,-1.131700e+04,0.000000e+00,0.000000e+00
25%,2020-08-17 00:00:00,0.000000e+00,8.300000e-01,4.040000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2020-12-31 00:00:00,2.000000e+00,3.710000e+00,1.271000e+01,0.000000e+00,0.000000e+00,0.000000e+00
75%,2021-05-16 00:00:00,1.200000e+01,1.400000e+01,3.337000e+01,0.000000e+00,2.900000e-01,4.300000e-01
max,2021-09-29 00:00:00,5.661000e+04,2.637233e+04,1.648350e+03,1.554000e+03,8.288600e+02,8.242000e+01
std,NaN,2.968251e+02,1.633520e+02,3.352340e+01,1.026638e+01,3.594971e+00,1.122688e+00

In [13]:
df.shape

(1774204, 10)